CREATE DATABASE VEHICULOS
USE VEHICULOS

CREATE TABLE Matriculas(
Id INT IDENTITY(1,1),
Numero VARCHAR(20) NOT NULL PRIMARY KEY, 
FechaExpedicion DATE NOT NULL, 
FechaVencimiento DATE NOT NULL, 
Estado BIT
)
GO

CREATE TABLE Conductor(
Id INT IDENTITY(1,1),
Identificacion VARCHAR(15) NOT NULL PRIMARY KEY,
Nombre VARCHAR(20) NOT NULL,
Apellido VARCHAR(20) NOT NULL,
Direccion VARCHAR(30),
Telefono VARCHAR(15),
Email VARCHAR(30),
FechaNacimiento DATE NOT NULL,
Estado BIT, 
MatriculaId VARCHAR(20) NOT NULL
CONSTRAINT FK_CONDUC_MATC FOREIGN KEY 
REFERENCES Matriculas(Numero)
ON UPDATE CASCADE
)
GO

CREATE TABLE Sanciones(
Id INT IDENTITY(1,1) PRIMARY KEY,
FechaActual DATE DEFAULT GETDATE(),
Sancion VARCHAR(100),
Observacion VARCHAR(MAX),
Valor DECIMAL(10,2),
ConductorId VARCHAR(15) NOT NULL
CONSTRAINT FK_SANC_COND FOREIGN KEY 
REFERENCES Conductor(Identificacion)
ON UPDATE CASCADE
)